name: Run Behave Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install behave selenium webdriver-manager

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_113.0.5672.92-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_113.0.5672.92-1_amd64.deb



      #      - name: Install Chromium
#        run: |
#          sudo apt update
#          sudo apt install -y chromium-browser

      - name: Run login.feature
        run: behave features/login.feature
