name: Run Behave Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install behave selenium webdriver-manager

      - name: Install Google Chrome 114
        run: |
          wget https://mirror.kraski.tv/soft/google_chrome/linux/114.0.5735.90/google-chrome-stable_114.0.5735.90-1_amd64.deb
          sudo apt install -y --allow-downgrades ./google-chrome-stable_114.0.5735.90-1_amd64.deb


      - name: Install ChromeDriver 114
        run: |
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Run login.feature
        run: behave features/login.feature
